version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./geoip.conf:/etc/nginx/conf.d/geoip.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
